---
chdir: "/root/nou2ube"
environment: production
address: 0.0.0.0
port: 80
timeout: 30
log: "log/thin-http.log"
pid: tmp/pids/thin-http.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
