---
chdir: "/root/nou2ube"
environment: production
socket: tmp/sockets/thin.sock
timeout: 30
log: "log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
