# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ef6b84e8f7b6c1ae90af3fb70cc064ab1e6a95ad0c1dd6f32be6f3a8e14e83ab46eb1dd0515d6aaa76097de304a51807757dc4c4632a13198db5e74f545009

test:
  secret_key_base: 7af5ea73a5394e327adb5f555fc237284661c6b35d9bb5a3e523a5e88322fdbff6c0643dd0c01d10972dc34c9e133de31c761e0771f36d67b9669356380766c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
